apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-app
  namespace: {{ .Values.environment.name }}-{{ .Chart.Name }}
  labels:
    {{- include "notejam.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "notejam.selectorLabels" . | nindent 4 }}
