# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#  name: notejam-pvc
#  namespace: prod-notejam
# spec:
#   storageClassName: local-storage
#   accessModes:
#     - ReadWriteMany
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 5Gi