name: Deploy notejam app to GKE

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      #- created
      - closed
    paths-ignore:
      - '**.md'
      - 'log/**'
      - '.github/**'

env:
  PROJECT_ID: "nord-project"
  GKE_CLUSTER: "nord-project-cluster"    # TODO: update to cluster name
  GKE_REGION: "us-central1-a"	   # TODO: update to cluster zone
#  DEPLOYMENT_NAME: "notejam-app" # TODO: update deployment name if changed in deployment.yaml
  IMAGE_NAME: "notejam"

jobs:
  build:
    name: Build/Push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          service_account_key: ${{ secrets.GCP_SA_CR_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - run: |-
          gcloud --quiet auth configure-docker

      - name: Login Docker
        uses: 'lagren/docker-gcr-action@master'
        with:
          SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_CR_KEY }}
          HOST: 'gcr.io'

      - uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_REGION }}
          credentials: ${{ secrets.GCP_SA_CR_KEY }}

      - name: Build the docker image and push to GCR
        run: |-
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          docker build -f Dockerfile -t gcr.io/$PROJECT_ID/notejam/$IMAGE_NAME:${GITHUB_REF##*/}-$git_hash .
          echo "Pushing image to GCR..."
          docker push gcr.io/$PROJECT_ID/notejam/$IMAGE_NAME:${GITHUB_REF##*/}-$git_hash
          echo "::set-output name=image::gcr.io/$PROJECT_ID/notejam/$IMAGE_NAME:${GITHUB_REF##*/}-$git_hash"

      - name: Update Version
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          version=$(cat ./k8s-deploy/values.yaml | grep version: | awk '{print $2}')
          sed -i "s/$version/${GITHUB_REF##*/}-$git_hash/" ./k8s-deploy/values.yaml

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Version updated

  deploy:
    name: Deploy to GKE
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Chekcout the latest version .
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_SA_CR_KEY }}

    - name: Install helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_REGION"

    - name: Deploy
      run: |-
        helm upgrade --install notejam ./k8s-deploy